apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-rules
  namespace: prometheus-grafana
data:
  alert_rules.yaml: |
    apiVersion: 1
    groups:
      - name: InstanceHighMemory
        interval: 1m
        rules:
          - uid: high_memory_usage
            title: High Memory Usage
            condition: B
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus
                model:
                  expr: (node_memory_Active_bytes / node_memory_MemTotal_bytes) * 100
                  format: time_series
                  interval: ""
                  intervalFactor: 2
                  legendFormat: "{{instance}}"
                  refId: A
              - refId: B
                datasourceUid: prometheus
                model:
                  reduce:
                    reducer: "last"
                    input: "A"
                  refId: B
            noDataState: Alerting
            execErrorState: Alerting
            for: 2m
            annotations:
              summary: "Memory usage is high on instance {{ $labels.instance }}"
            labels:
              severity: warning
